# Generated by Django 4.2.20 on 2025-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=50)),
                ('doctor_img', models.ImageField(height_field=100, upload_to='static/images', width_field=100)),
            ],
        ),
    ]
